name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run make command in ci folder
      run: cd lessons/ci/ && make hello

    - name: Run make command in make folder
      run: cd ../make && make hello